### ISSUE TITLE
Unable to fetch due to error pulling the image 

### ISSUE THREAD

**Issue by pittmanriley** [ersilia-os/eos74bo#28]
@GemmaTuron @emmakodes 

I'm having issues fetching the model -- when I fetch, it gives me this error: 

`🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

404 Client Error for http+docker://localhost/v1.43/images/ersiliaos/eos74bo:latest/json: Not Found ("No such image: ersiliaos/eos74bo:latest")`

Additionally, if I try manually pulling the image with the command `docker pull ersiliaos/eos74bo`, it says `no matching manifest for linux/arm64/v8 in the manifest list entries`

I'm not sure how to get this to work.

**Comment by pittmanriley** [comment]
I am starting to see that this is an issue for me with the other models as well. Additionally, @emmakodes helped me manually pull the image onto my computer with the command `docker pull --platform linux/amd64 ersiliaos/eos74bo`. While this successfully pulled the image, it briefly appeared in my Docker desktop but then when I tried to fetch the model again, it disappeared from my Docker images. Not sure what's going on here.

**Comment by miquelduranfrigola** [comment]
Thanks @pittmanriley 

If you look at our AirTable, https://airtable.com/shrNc3sTtTA3QeEZu, you'll see that for `eos74bo` an ARM64 image is not available, unfortunately.

There are few actions we need to take here:

- [ ] Could you check if `ersilia -v fetch eos3b5e` works for you? In this case, both ARM and AMD are available.
- [ ] We need to write a better **error message** than this... `404 Client Error for http+docker://localhost/v1.43/images/ersiliaos/eos74bo:latest/json: Not Found ("No such image: ersiliaos/eos74bo:latest")`. Maybe you can help me with this? I'd be happy to show you the logic behind raising good error messages in Ersilia, so you can support me when others have to do the same? Let me know.
- [ ] Could you please try `ersilia -v fetch eos74bo --from_github` ? This should fetch the model directly from GitHub, instead of the docker container. It is possible/probable that it will crash, but we'll have more capacity to inspect the error since we will have all files in the system instead of a docker container.

**Comment by pittmanriley** [comment]
Hi @miquelduranfrigola 

I was able to fetch the model eos3b5e, and it shows up on my DockerHub as well. However, I was still unable to fetch the model eos74bo with that new command you sent. 

Regarding the error messages, I'd love to help you with this. Please let me know how I can help!

**Comment by GemmaTuron** [comment]
Hi @pittmanriley ! 
thanks, we'll work on that together with @miquelduranfrigola 
I'll leave the issue open meanwhile

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I have been looking at old models I've tested to test again on the test module and found that this issue was still open. It is resolved, so we can close it! 

However, there's an inconsistency issue I found after testing it, so I opened a different one under this model.

**Comment by GemmaTuron** [comment]
Thanks @pittmanriley 
I'll close this and move the conversation to the other issue
